language: go
go:
  - master
  - stable
  - "1.11"
  - "1.10"
  - "1.9"
  - "1.8"
install:
  - go get github.com/randomingenuity/go-utility/...
  - go get -t ./...
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service=travis-ci
