language: go
go:
  - master
  - stable
  - "1.14"
  - "1.13"
  - "1.12"
env:
  - GO111MODULE=on
install:
  - go get -t ./...
script:
# v1
  - cd crypto
  - go test -v ./...
  - cd ../data
  - go test -v ./...
  - cd ../filesystem
  - go test -v ./...
  - cd ../geographic
  - go test -v ./...
  - cd ../image
  - go test -v ./...
  - cd ../testing
  - go test -v ./...
# v2
  - cd ../v2
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - cd ..
after_success:
  - cd v2
  - curl -s https://codecov.io/bash | bash
